name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install, build, and test
      - name: Install, Build, and Test Backend
        run: |
          npm install --workspaces=false
          npm run -w express-backend build --if-present
          npm run -w express-backend test --if-present
        working-directory: packages/express-backend
